### ISSUE TITLE
db

### ISSUE THREAD

**Issue by virusheureux** [404NotFoundIndonesia/laravel-surat-menyurat-v1#1]
databasenya gk ada ya?

**Comment by iqbaleff214** [comment]
Laravel sudah menyediakan fitur migration, skema databasenya sudah ada di sana semua, jadi saya rasa file .sql tidak diperlukan. Kalaupun ingin ada file .sql, bisa migrate database-nya di local computer / laptop kemudian export atau di-dump sesuai kebutuhan.
